// Product data and constants
export const PRODUCTS = [
	{
		id: 1,
		name: 'Orbital Vase No.7',
		cat: 'home',
		price: 28999,
		desc: 'A sculptural study in negative space. Fluid curvature meets mathematical precision. Printed at 0.05mm layer resolution — near-invisible surface topology.',
		badge: 'Limited',
		geom: 'vase',
		modelPath: '/assets/models/orbital-vase.glb',
		sketchfabId: 'a8f91f71faff45fdbea9fe0e88ae77a6',
		specs: [
			['Material', 'PETG Matte'],
			['Resolution', '0.05mm'],
			['Finish', 'Hand-polished'],
			['Ships In', '3–5 Days'],
			['Edition', '12 Units'],
		],
	},
	{
		id: 2,
		name: 'Helical Tower',
		cat: 'architectural',
		price: 43160,
		desc: 'Parametric stacking geometry. An architectural column at domestic scale. Twelve interleaving spirals resolve into a singular vertical statement.',
		badge: 'New',
		geom: 'helical',
		modelPath: '/assets/models/helical-tower.glb',
		sketchfabId: '9a59b82f98f34ae6a3a39b1b85c22fda',
		specs: [
			['Material', 'PLA+ Obsidian'],
			['Resolution', '0.08mm'],
			['Finish', 'Micro-polished'],
			['Ships In', '5–7 Days'],
			['Edition', '12 Units'],
		],
	},
	{
		id: 3,
		name: 'Void Sphere',
		cat: 'home',
		price: 23999,
		desc: 'Pure form. 800 intersecting planes creating structural void. A meditation on presence and absence rendered in precision polymer.',
		badge: '',
		geom: 'sphere',
		modelPath: '/assets/models/void-sphere.glb',
		sketchfabId: 'd425eb3d30bf435faa4b96b36e1a3ab3',
		specs: [
			['Material', 'PETG Pearl'],
			['Resolution', '0.06mm'],
			['Finish', 'Satin'],
			['Ships In', '3–5 Days'],
			['Edition', '24 Units'],
		],
	},
	{
		id: 4,
		name: 'Lattice Cuff',
		cat: 'wearables',
		price: 16199,
		desc: 'Wearable precision engineering. Printed at 0.08mm for micro-flex. The structure breathes with your movement — rigid yet alive.',
		badge: 'Sold Out',
		geom: 'ring',
		modelPath: '/assets/models/lattice-cuff.glb',
		sketchfabId: 'f8e0deaa28694e479bb01d8028da47cb',
		specs: [
			['Material', 'Flexible TPU'],
			['Resolution', '0.08mm'],
			['Finish', 'Raw texture'],
			['Ships In', '7–10 Days'],
			['Edition', '30 Units'],
		],
	},
	{
		id: 5,
		name: 'Arc Plinth',
		cat: 'architectural',
		price: 59760,
		desc: 'A plinth that is itself the sculpture. Monolithic black. The base becomes the statement — commanding negative space with gravitational authority.',
		badge: 'Limited',
		geom: 'vase',
		modelPath: '/assets/models/arc-plinth.glb',
		sketchfabId: '1e1d7b4d5e374a8db97de8a6fc0ef0dc',
		specs: [
			['Material', 'PLA Matte Black'],
			['Resolution', '0.05mm'],
			['Finish', '12-step hand finish'],
			['Ships In', '7–10 Days'],
			['Edition', '8 Units'],
		],
	},
	{
		id: 6,
		name: 'Moiré Pendant',
		cat: 'wearables',
		price: 13944,
		desc: 'Optical interference made wearable. Two concentric lattice layers produce shifting moiré patterns as light and angle change.',
		badge: '',
		geom: 'torus',
		modelPath: '/assets/models/moire-pendant.glb',
		sketchfabId: 'b07ad48b1b9941939e9a9d9c93c5ea73',
		specs: [
			['Material', 'Transparent PETG'],
			['Resolution', '0.07mm'],
			['Finish', 'Clear-coat'],
			['Ships In', '3–5 Days'],
			['Edition', '48 Units'],
		],
	},
	{
		id: 7,
		name: 'Fractal Bowl',
		cat: 'home',
		price: 25896,
		desc: 'Infinitely complex surface topology. L-system branching resolved at 0.05mm render depth. A functional object that rewards prolonged study.',
		badge: 'New',
		geom: 'sphere',
		modelPath: '/assets/models/fractal-bowl.glb',
		sketchfabId: '3b33e7b0d57041d79ea7ef6a65534e1b',
		specs: [
			['Material', 'PETG Frost'],
			['Resolution', '0.05mm'],
			['Finish', 'Sanded + sealed'],
			['Ships In', '5–7 Days'],
			['Edition', '12 Units'],
		],
	},
	{
		id: 8,
		name: 'Column Series I',
		cat: 'architectural',
		price: 73870,
		desc: 'Architectural column at 1:10 scale. Museum-grade finish. Twelve fluted ribs dissolve into a capital of impossible delicacy at 0.04mm.',
		badge: 'Limited',
		geom: 'helical',
		modelPath: '/assets/models/column-series.glb',
		sketchfabId: 'c8f5c5d3a2c74c21abfae30ffd4cef3c',
		specs: [
			['Material', 'PLA+ Marble'],
			['Resolution', '0.04mm'],
			['Finish', 'Automotive grade'],
			['Ships In', '10–14 Days'],
			['Edition', '6 Units'],
		],
	},
	{
		id: 9,
		name: 'Mesh Ring',
		cat: 'wearables',
		price: 12035,
		desc: 'Parametric mesh structure. Sized to order. 340 interconnected nodes — individually modelled and resolved into a unified wearable topology.',
		badge: '',
		geom: 'ring',
		modelPath: '/assets/models/mesh-ring.glb',
		sketchfabId: 'f8e0deaa28694e479bb01d8028da47cb',
		specs: [
			['Material', 'Nylon PA12'],
			['Resolution', '0.08mm'],
			['Finish', 'Natural'],
			['Ships In', '5–7 Days'],
			['Edition', 'Unlimited'],
		],
	},
];

export const CATEGORIES = ['all', 'home', 'architectural', 'wearables'];
