// Product data and constants — StudioForm Hero Products
export const PRODUCTS = [
	{
		id: 1,
		name: 'Premium Architectural Nameplate',
		cat: 'nameplates',
		price: 4500,
		priceRange: '₹2,500 – ₹8,000',
		desc: 'Elevate your entrance with a bespoke 3D-printed nameplate. Precision-engineered from premium PLA+ with metallic finish options. Each piece is custom-designed with your family name, house number, and motif — crafted to last decades.',
		badge: 'Bestseller',
		image: '/images/products/nameplate.png',
		modelPath: null,
		variants: [
			{ name: 'Classic Black', price: 2500 },
			{ name: 'Gold Accent', price: 4500 },
			{ name: 'Premium Duo-Tone', price: 6000 },
			{ name: 'Luxury Metallic', price: 8000 },
		],
		specs: [
			['Material', 'PLA+ / PETG with metallic finish'],
			['Size', '30cm × 15cm × 2cm (customizable)'],
			['Resolution', '0.08mm layer height'],
			['Finish', 'Hand-polished, UV-resistant coating'],
			['Ships In', '5–7 Business Days'],
			['Customization', 'Name, number, font, motif'],
		],
	},
	{
		id: 2,
		name: 'Birth Stats Baby Milestone Plaque',
		cat: 'milestones',
		price: 5000,
		priceRange: '₹3,500 – ₹7,000',
		desc: 'Celebrate the arrival of your little one with a handcrafted milestone plaque. Features birth date, time, weight, length, and name in an elegant circular design with pastel tones and gold accents. A keepsake that grows more precious with time.',
		badge: 'New',
		image: '/images/products/milestone.png',
		modelPath: null,
		variants: [
			{ name: 'Pastel Circle', price: 3500 },
			{ name: 'Gold Frame', price: 5000 },
			{ name: 'Premium 3D Relief', price: 7000 },
		],
		specs: [
			['Material', 'PLA+ with food-safe coating'],
			['Size', '25cm diameter × 1.5cm'],
			['Resolution', '0.06mm layer height'],
			['Finish', 'Satin smooth, pastel + gold accent'],
			['Ships In', '5–7 Business Days'],
			['Customization', 'Name, DOB, weight, time, length'],
		],
	},
	{
		id: 3,
		name: 'Contemporary Ganesha Sculpture',
		cat: 'spiritual',
		price: 8000,
		priceRange: '₹4,000 – ₹15,000',
		desc: 'A modern reinterpretation of Lord Ganesha — where devotion meets contemporary design. Geometric facets and clean lines create a striking spiritual presence for modern homes. Available in matte black, marble white, and metallic gold finishes.',
		badge: 'Limited',
		image: '/images/products/ganesha.png',
		modelPath: null,
		variants: [
			{ name: 'Matte Black (6")', price: 4000 },
			{ name: 'Marble White (8")', price: 8000 },
			{ name: 'Metallic Gold (8")', price: 12000 },
			{ name: 'Premium Large (12")', price: 15000 },
		],
		specs: [
			['Material', 'PLA+ with premium coating'],
			['Sizes', '6", 8", or 12" height'],
			['Resolution', '0.05mm layer height'],
			['Finish', 'Multi-step hand finishing'],
			['Ships In', '7–10 Business Days'],
			['Edition', 'Limited run per finish'],
		],
	},
	{
		id: 4,
		name: 'Premium Desk Organizer Set',
		cat: 'desk',
		price: 3500,
		priceRange: '₹2,000 – ₹6,000',
		desc: 'Transform your workspace with precision-engineered desk accessories. Clean geometric forms, modular design. Includes pen holder, card stand, and cable organizer — all designed to nest together or stand independently.',
		badge: '',
		image: '/images/products/desk-organizer.png',
		modelPath: null,
		variants: [
			{ name: 'Essential (3-piece)', price: 2000 },
			{ name: 'Professional (5-piece)', price: 3500 },
			{ name: 'Executive (7-piece)', price: 6000 },
		],
		specs: [
			['Material', 'PETG with soft-touch coating'],
			['Finish', 'Matte black / Walnut accent'],
			['Resolution', '0.08mm layer height'],
			['Design', 'Modular, stackable geometry'],
			['Ships In', '3–5 Business Days'],
			['Includes', 'Pen holder, card stand, cable org'],
		],
	},
	{
		id: 5,
		name: 'Architectural Wedding Gift Object',
		cat: 'wedding',
		price: 12000,
		priceRange: '₹8,000 – ₹20,000',
		desc: 'An heirloom-grade gift for the most important day. Abstract intertwined rings symbolize eternal union. Available in metallic gold, rose gold, and pearl white — each piece comes with a premium gift box and personalized message plate.',
		badge: 'Premium',
		image: '/images/products/wedding-gift.png',
		modelPath: null,
		variants: [
			{ name: 'Pearl White', price: 8000 },
			{ name: 'Metallic Gold', price: 12000 },
			{ name: 'Rose Gold', price: 14000 },
			{ name: 'Luxury Duo (Gold + Pearl)', price: 20000 },
		],
		specs: [
			['Material', 'PLA+ with metallic coating'],
			['Size', '20cm × 15cm × 12cm'],
			['Resolution', '0.04mm layer height'],
			['Finish', 'Automotive-grade metallic'],
			['Ships In', '10–14 Business Days'],
			['Includes', 'Premium box, message plate'],
		],
	},
];

export const CATEGORIES = ['all', 'nameplates', 'milestones', 'spiritual', 'desk', 'wedding'];
